### PR TITLE
[WIP] More travis debugging

### PR DESCRIPTION
**Pull request by ChayaSt**
see https://github.com/choderalab/torsionfit/pull/28#issuecomment-212980551

### CODE REVIEW

**Comment by ChayaSt** [comment]
Python 2.7 passes. I'm running into this error in python 3.4

```======================================================================
ERROR: test_yrestore_state (torsionfit.tests.test_backends.TestSqlitePlus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/torsionfit/tests/test_backends.py", line 73, in test_yrestore_state
    db = self.load()
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/torsionfit/tests/test_backends.py", line 65, in load
    return sqlite_plus.load(os.path.join(testdir, 'Disaster.sqlite'))
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/torsionfit/sqlite_plus.py", line 272, in load
    db = Database(dbname)
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/torsionfit/sqlite_plus.py", line 206, in __init__
    self._chains[row[0]] = pickle.loads(str(row[1]))
TypeError: 'str' does not support the buffer interface
```

**Comment by jchodera** [comment]
Looks like others have run into this too:
http://stackoverflow.com/questions/5471158/typeerror-str-does-not-support-the-buffer-interface

**Comment by jchodera** [comment]
The python 3 errors are all
```
TypeError: 'str' does not support the buffer interface
```
The suggested solution from [this page](http://stackoverflow.com/questions/5471158/typeerror-str-does-not-support-the-buffer-interface) is
>If you use Python3x then string is not the same type as for Python 2.x, you must cast it to bytes (encode it).
```
plaintext = input("Please enter the text you want to compress")
filename = input("Please enter the desired filename")
with gzip.open(filename + ".gz", "wb") as outfile:
    outfile.write(bytes(plaintext, 'UTF-8'))
```

**Comment by ChayaSt** [comment]
I get the following error on linux python 3.5:

```
======================================================================
ERROR: Failure: ImportError (libopenblas.so.0: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/miniconda/envs/_test/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/travis/miniconda/envs/_test/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/torsionfit/tests/test_backends.py", line 8, in <module>
    from pymc.examples import disaster_model
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/home/travis/miniconda/envs/_test/lib/python3.5/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```
I tried the solution here:
https://github.com/sermanet/OverFeat/issues/10#issuecomment-40912417

I added these lines to ```.travis.yml``` : 
```
before_install:
 - sudo apt-get install libopenblas-base
 - export LD_LIBRARY_PATH=/usr/lib/openblas-base/
```
which fixed the failure and the tests passed. But it broke the osx build. But when I added an if statement, it doesn't seem to be installing openBLAS and I'm getting the same travis failure again.

**Comment by jchodera** [comment]
You shouldn't need to install libraries like that---they should be pulled directly with conda.  Let's look for an alternate solution.

The issue seems to be that the `pymc` conda package doesn't bring in all the dependencies it needs for `flib`.  What channel is the `pymc` conda package coming from?  Is it from `omnia`?

**Comment by ChayaSt** [comment]
> What channel is the pymc conda package coming from? Is it from omnia?

It's not coming from ```omnia```. It's coming from the conda repositories.

**Comment by ChayaSt** [comment]
I'm also getting the following error with python 3.4 on OSX

```
 conda build devtools/conda-recipe
Removing old build environment
Removing old work directory
BUILD START: torsionfit-dev-0.0.0-py34_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ....
TEST START: torsionfit-dev-0.0.0-py34_0
Fetching package metadata: ........
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - torsionfit-dev 0.0.0 py34_0
```
However, the thing is that in this [travis build](https://travis-ci.org/choderalab/torsionfit/jobs/124791880), it didn't have a problem finding the package:
[Here's](https://github.com/choderalab/torsionfit/blob/cdd1b1b72b53ce7fc0c541d317fe257f7f0ff68b/devtools/conda-recipe/meta.yaml)  the ```meta.yaml`` file for that build. It doesn't look any different from the [current](https://github.com/ChayaSt/torsionfit/blob/travis/devtools/conda-recipe/meta.yaml) file. The other files in the conda-recipe have also not been changed.

**Comment by jchodera** [comment]
> It's not coming from omnia. It's coming from the conda repositories.

Which one?  There are a lot of them:

https://anaconda.org/search?q=pymc

Is it the `anaconda` one?

**Comment by jchodera** [comment]
> However, the thing is that in this travis build, it didn't have a problem finding the package:

Travis doesn't build for `osx`---only `linux64`.

**Comment by ChayaSt** [comment]
> Travis doesn't build for osx---only linux64.

It looks like it is building for osx. https://travis-ci.org/choderalab/torsionfit/jobs/128950086#L44

**Comment by ChayaSt** [comment]
> Is it the anaconda one?

I think it's this one https://repo.continuum.io/pkgs/free/linux-64/
There's only one pymc 2.3.4 for python 3.5

**Comment by jchodera** [comment]
> It looks like it is building for osx. https://travis-ci.org/choderalab/torsionfit/jobs/128950086#L44

You're right!  Huh.  I hadn't realized we did that.

**Comment by jchodera** [comment]
I think this is the `pymc` you are using.  Let me see if I can figure out what the dependency issue is.

**Comment by jchodera** [comment]
> I get the following error on linux python 3.5:

Do you know which `numpy` version you are using?

**Comment by ChayaSt** [comment]
> Do you know which numpy version you are using?

It's using numpy 1.9.3 for python 3.5
https://travis-ci.org/choderalab/torsionfit/jobs/128950083#L295

**Comment by jchodera** [comment]
I was able to install `pymc` via `conda install --yes pymc` on miniconda Python 3.5 on `linux` and I don't seem to get that error message:
```
[chodera@gpu-1-4 ~]$ python
imPython 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc
>>> from pymc.examples import disaster_model
>>> 
```
It brought in the `numpy 1.1.1` version by default, though.

**Comment by jchodera** [comment]
I can confirm that forcing numpy 1.9.3 gives the same error you see:
```
[chodera@gpu-1-4 ~]$ python
iPython 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

**Comment by jchodera** [comment]
For now, what do you think of just forcing an upgrade to numpy 1.11 with
```bash
conda install --yes numpy==1.11
```
?

**Comment by jchodera** [comment]
Otherwise, if you need to stick with numpy 1.9.3, I found this works:
```bash
conda install --yes libgfortran==1.0 openblas
```

**Comment by ChayaSt** [comment]
> Otherwise, if you need to stick with numpy 1.9.3, I found this works:

I need numpy 1.9.3 for pymc. I tried adding that line to [here](https://github.com/ChayaSt/torsionfit/blob/travis/.travis.yml#L24) but I'm still getting the same error. I also tried to add it to the ```meta.yaml``` file but then I got [this](https://travis-ci.org/choderalab/torsionfit/jobs/129225400#L542-L543)

**Comment by jchodera** [comment]
You can install `pymc` with numpy `1.11` just fine:
```bash
conda install --yes pymc numpy==1.11
```
installs `pymc` and `numpy` 1.11, and works fine:
```
[chodera@gpu-2-17 ~]$ python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc
>>> 
```

**Comment by ChayaSt** [comment]
I'm getting conflicts here:

https://travis-ci.org/choderalab/torsionfit/jobs/129241705#L313-L318

**Comment by jchodera** [comment]
Ah!  `anaconda` has moved onto numpy 1.11 support while `omnia` is still only at 1.10 support.  Try numpy 1.10? 

In the meantime, I'll add numpy 1.11 support to `omnia`. Will take a few days.

**Comment by ChayaSt** [comment]
I'm still getting conflicts with numpy 1.10

https://travis-ci.org/choderalab/torsionfit/jobs/129243429#L183-L186

**Comment by jchodera** [comment]
Oh, I think you have to remove the `==2.3.4` constraint on `pymc`.

**Comment by ChayaSt** [comment]
Whew! This fixed it! Thanks! 

But I'm still getting [this](https://travis-ci.org/choderalab/torsionfit/jobs/129268122#L173-L174) error for python 3.4 on OSX

**Pull request merged**
