### PR TITLE
Netcdf4 backend

### PR DESCRIPTION
**Pull request by ChayaSt**

### CODE REVIEW

**Comment by jchodera** [comment]
You have a `netCDF4` import error, so I think you need to add `netcdf4` to the `build` and `run` dependencies in your `meta.yaml` file:
https://github.com/choderalab/torsionfit/blob/master/devtools/conda-recipe/meta.yaml

**Comment by ChayaSt** [comment]
This is the error I get when creating netcdf4 variable using datatype 'S'.  It should allow storing arbitrary data type because it converts it to a pickled string.

```
Error message:
Traceback (most recent call last):
  File "/Users/sternc1/anaconda/envs/py3k/lib/python3.4/site-packages/pymc/Model.py", line 777, in save_state
    self.db.savestate(self.get_state())
  File "/Users/sternc1/src/ChayaSt/Torsions/torsionfit/netcdf4.py", line 251, in savestate
    self.ncfile['Chain#%d' % chain].createVariable('state', 'S', ('state',))
  File "netCDF4/_netCDF4.pyx", line 2145, in netCDF4._netCDF4.Dataset.createVariable (netCDF4/_netCDF4.c:16197)
  File "netCDF4/_netCDF4.pyx", line 2978, in netCDF4._netCDF4.Variable.__init__ (netCDF4/_netCDF4.c:26930)
TypeError: illegal primitive data type, must be one of dict_keys(['f8', 'i2', 'u4', 'u8', 'u1', 'f4', 'S1', 'u2', 'i8', 'i4', 'U1', 'i1']), got |S0
Warning, unable to save state.
```

**Comment by jchodera** [comment]
What tests are you running?

**Comment by jchodera** [comment]
Found them!  Having trouble installing a working `pymc`, though.

**Comment by ChayaSt** [comment]
Did you try installing pymc with conda?

**Comment by jchodera** [comment]
Yep, but I don't have the `gfortran` libraries installed in `/usr/local/gcc` (and am hoping to avoid this):
```
mski1776:Torsions.chayast choderaj$ python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pymc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: dlopen(/Users/choderaj/miniconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/flib.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgfortran.3.dylib
  Referenced from: /Users/choderaj/miniconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/flib.so
  Reason: image not found
```

**Comment by ChayaSt** [comment]
I had a similar issue at some point. I think this happens when you try to install pymc with setup.py from torsionfit, but I'm not sure why. Try removing this one and do conda install pymc=2.3.4.

**Comment by jchodera** [comment]
I've checked that I don't have `pymc` installed via other means.  Still debugging...

**Comment by jchodera** [comment]
Reinstalling `miniconda` fixed it!

**Comment by jchodera** [comment]
Huh.  Somehow, installing one of the dependencies for `torsionfit` via conda breaks `pymc`.

**Comment by ChayaSt** [comment]
Huh? This is weird.

**Comment by ChayaSt** [comment]
I think I fixed it!

**Comment by ChayaSt** [comment]
Encoding the pickled object to text (base64) seems to work.

**Comment by jchodera** [comment]
Awesome!  Weird, but glad it was fixed.

**Pull request merged**
