### PR TITLE
[WIP] speeding up sampler

### PR DESCRIPTION
**Pull request by ChayaSt**
The sampler is slow. See issue https://github.com/choderalab/torsionfit/issues/23

```structure.createSystem(param)``` is the slowest step. It's already cached for each updated ```param```.  What I am trying  to do is to cache the system and context for the structure, and use ```updateParametersInContext``` for each updated ```param```  instead of calling ```structure.createSystem(param)```

It's not working yet. Instead of using Parmed's ```structure.createSystem(param)```, I parameterize the structure with the updated ```param```, then create ```OpenMM: :PeriodicTorsionForce``` with ```structure.omm_diehdral_force```. I use this force to ```updateParametersInContext(self.context)``` 

I am probably doing it wrong or missing something because I am getting the following error:
```Exception: getImplInContext: This Force is not present in the Context``

### CODE REVIEW

**Comment by jchodera** [comment]
In order for `force.updateParametersInContext(context)` to work, the `force` object you are calling this function for must be present in the `System` object that the `context` was created from.  If you create a *new* force object using `omm_dihedral_force()`, this isn't true. 

What you will need to do is to first copy the parameters from the new force to the old force, then call `updateParametersInContext()` for the old force that was present in the `System` object the `context` was created from.

**Comment by jchodera** [comment]
You probably also want to add a sanity check to make sure that the torsion atoms still match up between the old and new torsion forces.  If these get reordered, things will get crazy.

**Comment by ChayaSt** [comment]
I was chatting with @gregoryross about speeding up the evaluation of energy with the new parameters and this is what we thought would be more efficient than evaluating the entire energy of the system:

1. First evaluate the contribution to the potential energy of each force using ParmEd's ```energy_decomposition_system``` function. 
2. store the energy for each force in a vector 
3. write a function that evaluates only the torsion force. This should be fast with numpy. Or if it's not fast enough, we can try numba or cython to speed it up.  

This will then be easy to extend for other parameters that we will want to sample in the future.

**Comment by jchodera** [comment]
We could definitely evaluate just the torsion forces outside of `OpenMM`, but we lose a great deal of generality by doing so.  For this purpose, it may be fine, however---we are only sampling the torsion terms for a well-defined Fourier series. But when we eventually want to combine this approach with Bayesian forcefield parameterization for other terms, they will also be changing during the sampling procedure, and it helps to have the generality of OpenMM-computed forces.

**Comment by ChayaSt** [comment]
> What you will need to do is to first copy the parameters from the new force to the old force, then call updateParametersInContext() for the old force that was present in the System object the context was created from.

What would be the fastest way to do this? From looking at the system, I can remove the force and the new force I created. Is this the best way to do this?

Another thing we can do to speed up the energy evaluation is by splitting the Force object into groups and only evaluating the ```PeriodicTorsionForce```. 

I still think the approach here https://github.com/choderalab/torsionfit/pull/25#issuecomment-201392322 will be faster. We will lose generality for the Non-bonded forces, but aren't all the bonded forces well defined functions? So we wouldn't lose generality there.

**Comment by ChayaSt** [comment]
> What you will need to do is to first copy the parameters from the new force to the old force, then call updateParametersInContext() for the old force that was present in the System object the context was created from.

I did this but it didn't speed up the sampling. Now the slow step is [```load_parameters```](https://github.com/ChayaSt/torsionfit/blob/fragments/torsionfit/TorsionScanSet.py#L177).

**Comment by jchodera** [comment]
@swails may have some idea about how to speed that part up.

Another possibility is, as you suggested earlier, just create a separate system and parameter set that only has torsions.  You can use the full system without torsions to compute the (static) contribution to the energy from all other parameters, and then only sample over the torsion-relevant force term and parameters.  That might speed everything up.

**Comment by swails** [comment]
> I did this but it didn't speed up the sampling. Now the slow step is load_parameters.

I suspect [this is the reason it's so slow](https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/psf.py#L476).  Every time you call `load_parameters`, it makes a deep copy of the entire parameter set before assigning them.  If your parameter set is large (and you don't use many of the parameters), then this can get pretty expensive, especially if it's supposed to be high-throughput.

This is done for safety.  `load_parameters` assigns types via references, and these references are used to "compress" the type list that is assigned for each parameter.  So if you didn't do that copy, then any time you modified the original parameter set, it would silently modify the references in the Structure list_types as well, which is surprising behavior.

However, if you have this in the back of your mind and design a strategy where this behavior won't affect you, then you can probably comment-out the `_copy(parmset)` line and achieve a massive speed-up.  Some alternative approaches are

1. Only copy the parameters we actually plan on using.  This may still be slow, and would take a little work to avoid making duplicate parameters for every single term in the system (which would balloon the size of an Amber prmtop file, for instance).
2. Work with a copy of the parameter set that *only* has the set of parameters you are actually using for your system so that the deep copy is much faster.

Of 1 and 2, I'd opt for 2 since it doesn't require any code changes and may very well be faster than 1.  To do this, create a `Structure`, call `load_parameters` on it once at the beginning with the whole parameter set, then do

```Python
params = pmd.charmm.CharmmParameterSet.from_structure(struct)
```

That is the new parameter set that contains only the parameters used in your particular molecule.  If you just stick with using this set of parameters, it should hopefully speed things up significantly.

If the above suggestion doesn't work, then you'll really have to use `cProfile` to get a much finer picture of where the performance bottlenecks are.  Optimizing without a profiler is madness! :).  And `cProfile` is very easy to use:

```
bash$ python -m cProfile your_script.py <arguments>
```

**Comment by ChayaSt** [comment]
> Work with a copy of the parameter set that only has the set of parameters you are actually using for your system so that the deep copy is much faster.

Thanks @swails! This fix gave me a 10X speedup!

**Comment by swails** [comment]
Wow! Nice! Is the performance acceptable now, or still too slow?

**Comment by ChayaSt** [comment]
> Wow! Nice! Is the performance acceptable now, or still too slow?

It's OK for a small data set, but it still becomes very slow when the data set (molecules and parameters) increase. After the PR is merged, I'll work on parallelizing the energy evaluation.

**Comment by ChayaSt** [comment]
> This is done for safety. load_parameters assigns types via references, and these references are used to "compress" the type list that is assigned for each parameter. So if you didn't do that copy, then any time you modified the original parameter set, it would silently modify the references in the Structure list_types as well, which is surprising behavior.

@swails, this behavior is actually something I want. Right now I update the ```parameterSet``` and then reparameterize the structure with load_parameters. But if I get rid of the copy, I can avoid doing this and just keep on updating the original ```parameterSet```. This will speed up the sampler a lot because right now ```load_parameters``` is still the bottleneck. Can we add an option to ```load_parameters``` not to copy ```ParameterSet```?

**Comment by swails** [comment]
Sure. Just default it to True

**Comment by swails** [comment]
Actually first to me a favor and profile at how much of a difference does it really make?
I'm not against the idea. I just want an idea of the cost of this operation.

**Comment by ChayaSt** [comment]
OK. Sure.

**Comment by ChayaSt** [comment]
This is a profile of one sample MCMC step
```copy_torsion``` calls ```structure.load_parameters``` with the sub parameterSet.

In this output, ```_copy(paramset)``` is not commented out. 
``` 
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000    5.546    5.546 /Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/MCMC.py:199(sample)
156    0.052    0.000    4.022    0.026 /Users/sternc1/anaconda/lib/python2.7/site-packages/torsionfit-0+untagged.214.g8b51808.dirty-py2.7.egg/torsionfit/TorsionScanSet.py:188(copy_torsions)
158    0.108    0.001    1.750    0.011 /Users/sternc1/anaconda/lib/python2.7/site-packages/ParmEd-2.4.4-py2.7-macosx-10.5-x86_64.egg/parmed/charmm/psf.py:453(load_parameters)
```
with copy commented out
```
ncalls  tottime  percall  cumtime  percall filename
1    0.000    0.000    4.578    4.578 /Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/MCMC.py:199(sample)
147    0.045    0.000    3.176    0.022 /Users/sternc1/anaconda/lib/python2.7/site-packages/torsionfit-0+untagged.214.g8b51808.dirty-py2.7.egg/torsionfit/TorsionScanSet.py:188(copy_torsions)
149    0.095    0.001    0.260    0.002 /Users/sternc1/anaconda/lib/python2.7/site-packages/ParmEd-2.4.4-py2.7-macosx-10.5-x86_64.egg/parmed/charmm/psf.py:453(load_parameters)
```
Here I'm not loading parameters when updating parameters. I'm relying on the 'silent' change so I only create the new force ```new_force = structure.omm_dihedral_force()``` to copy into the torsions force in the system

```
ncalls  tottime  percall  cumtime  percall filename
1    0.000    0.000    4.033    4.033 /Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/MCMC.py:199(sample)
137    0.041    0.000    2.721    0.020 /Users/sternc1/anaconda/lib/python2.7/site-packages/torsionfit-0+untagged.214.g8b51808.dirty-py2.7.egg/torsionfit/TorsionScanSet.py:188(copy_torsions)
2    0.001    0.001    0.004    0.002 /Users/sternc1/anaconda/lib/python2.7/site-packages/ParmEd-2.4.4-py2.7-macosx-10.5-x86_64.egg/parmed/charmm/psf.py:453(load_parameters)
```

Looking at this output, I'm not really sure why ncalls to copy_torsion is changing...

**Comment by swails** [comment]
I see.  Yea, that's a pretty substantial time savings.  Go ahead and submit a PR for it (make sure you bump the version up a level for this).

**Comment by ChayaSt** [comment]
I'm getting this travis error and I'm not sure why it's happening. This happens when test_torsionFitModel.py tries to set up the pymc model. It fails at ```self.mm_energy.min()```
All the tests pass on my computer. At first I thought it was a numpy version problem. But I tried changing that and I'm still getting the same error. 

```
======================================================================
ERROR: Failure: ValueError (zero-size array to reduction operation minimum which has no identity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/tests/test_torsionFitModel.py", line 30, in <module>
    model = TorsionFitModel(param, stream, frag, platform=platform)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionFitModel.py", line 101, in __init__
    def mm_energy(pymc_parameters=self.pymc_parameters, param=param):
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/InstantiationDecorators.py", line 250, in deterministic
    return instantiate_n(__func__)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/InstantiationDecorators.py", line 243, in instantiate_n
    return Deterministic(parents=parents, **kwds)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 443, in __init__
    verbose=verbose)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/Node.py", line 214, in __init__
    Node.__init__(self, doc, name, parents, cache_depth, verbose=verbose)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/Node.py", line 129, in __init__
    self.parents = parents
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/Node.py", line 147, in _set_parents
    self.gen_lazy_function()
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 454, in gen_lazy_function
    self._value.force_compute()
  File "LazyFunction.pyx", line 257, in pymc.LazyFunction.LazyFunction.force_compute (pymc/LazyFunction.c:2409)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionFitModel.py", line 106, in mm_energy
    platform=self.platform)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionScanSet.py", line 252, in compute_energy
    self.mm_energy -= self.mm_energy.min() + Quantity(value=float(offset.value), unit=kilojoules_per_mole)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/unit/quantity.py", line 560, in min
    mymin = self._value.min(*args, **kwargs)
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by jchodera** [comment]
Thanks!  I'll see if I can debug in a separate PR.

**Pull request merged**
