### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by ChayaSt**
cclib throws out structures that didn't converge but keeps the energy. TorsionScanSet now removes the extra energies that don't have corresponding structures.

### CODE REVIEW

**Comment by jchodera** [comment]
Good catch!

Does this fix the discrepancy between RMS error and `sigma` we were seeing earlier?

**Comment by ChayaSt** [comment]
It didn't fix that problem. I'll continue debugging.

**Comment by jchodera** [comment]
Does this still need to be merged?

**Comment by ChayaSt** [comment]
Yes, we should merge this.

**Pull request merged**
