### PR TITLE
[WIP] Update conda dev recipe to address travis failures

### PR DESCRIPTION
**Pull request by jchodera**
I'm tinkering with the conda dev recipe to try to fix the travis failures.

### CODE REVIEW

**Comment by jchodera** [comment]
I see errors like this too:
```
======================================================================
ERROR: Failure: ImportError (cannot import name PyMCObjects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/tests/test_torsionFitModel.py", line 5, in <module>
    from torsionfit.TorsionFitModel import TorsionFitModel
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionFitModel.py", line 1, in <module>
    import pymc
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 13, in <module>
    from . import PyMCObjects as pm
ImportError: cannot import name PyMCObjects
```
Looks like this might be an issue with this version of `pymc`?

**Comment by jchodera** [comment]
@ChayaSt : I've found the cause of your travis failures!  You had created an empty `TorsionScanSet`, which meant that the empty set had no minimum for the `.min()` operation.  I now throw an `Exception` if you try to create an empty `TorsionScanSet`.

I've made a number of improvements in this PR---mostly to the conda recipe---so I suggest you merge it and fix the empty `TorsionScanSet` issue in the tests.

**Comment by ChayaSt** [comment]
I did a clean checkout and testing. I'm getting the following error: 
```
Failure: AttributeError ('Uniform' object has no attribute 'unit') ... ERROR

======================================================================
ERROR: Failure: AttributeError ('Uniform' object has no attribute 'unit')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sternc1/torsionfit/torsionfit/tests/test_torsionFitModel.py", line 30, in <module>
    model = TorsionFitModel(param, stream, frag, platform=platform)
  File "/Users/sternc1/torsionfit/torsionfit/TorsionFitModel.py", line 101, in __init__
    def mm_energy(pymc_parameters=self.pymc_parameters, param=param):
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/InstantiationDecorators.py", line 250, in deterministic
    return instantiate_n(__func__)
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/InstantiationDecorators.py", line 243, in instantiate_n
    return Deterministic(parents=parents, **kwds)
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 442, in __init__
    verbose=verbose)
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/Node.py", line 219, in __init__
    Node.__init__(self, doc, name, parents, cache_depth, verbose=verbose)
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/Node.py", line 129, in __init__
    self.parents = parents
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/Node.py", line 152, in _set_parents
    self.gen_lazy_function()
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 453, in gen_lazy_function
    self._value.force_compute()
  File "LazyFunction.pyx", line 257, in pymc.LazyFunction.LazyFunction.force_compute (pymc/LazyFunction.c:2409)
  File "/Users/sternc1/torsionfit/torsionfit/TorsionFitModel.py", line 106, in mm_energy
    platform=self.platform)
  File "/Users/sternc1/torsionfit/torsionfit/TorsionScanSet.py", line 265, in compute_energy
    self.mm_energy += offset
  File "/Users/sternc1/anaconda/lib/python2.7/site-packages/simtk/unit/quantity.py", line 234, in __add__
    if not self.unit.is_compatible(other.unit):
AttributeError: 'Uniform' object has no attribute 'unit'
```
Changing line 265 to : 
```self.mm_energy += Quantity(value=offset.value, unit=kilojoules_per_mole)```

But as you mentioned [here](https://github.com/choderalab/torsionfit/issues/27#issuecomment-212544631), we really shouldn't need to do this.

**Comment by jchodera** [comment]
You shouldn't have pymc stochastics that are unit bearing quantities. Why
not make "offset" be a float with fixed units and then add them later?

**Pull request merged**
