### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ChayaSt**
Updated README and removed extraneous files.

### CODE REVIEW

**Comment by jchodera** [comment]
Why remove Python 3.6?

**Comment by ChayaSt** [comment]
There is currently a conflict with some of the dependencies and python 3.6 that I'm trying to sort out. libgfortran 1.0.0 conflicts with numpy 1.11. But numpy 1.10 conflicts with python 3.6.

**Comment by jchodera** [comment]
Your travis is out of date. Note that [this line](https://github.com/ChayaSt/torsionfit/blob/3695d5c3367bff1383ce6d3563d5d33a6bdc5425/.travis.yml#L22) just adds `omnia`, but `omnia` requires `conda-forge` which should resolve your conflicts.

**Comment by jchodera** [comment]
See the updated `omnia` installation instructions [here](http://www.omnia.md/install/).

Make sure your travis does this:
```bash
# Add conda-forge and omnia to your channel list
conda config --add channels omnia --add channels conda-forge
# Update conda
conda update --yes conda
```

**Comment by ChayaSt** [comment]
Thanks! This resolved the conflict for Python 3.6 but introduced some new conflicts for Python 3.4 so I'm removing support for Python 3.4.

**Comment by jchodera** [comment]
Sounds great. Omnia supports the last two releases of Python (3.5 and 3.6) and Python 2.7 (though our lab has dropped support for 2.7).

**Pull request merged**
